name: Deploy React Frontend to Cloud Run
 
on:
  workflow_dispatch:
 
env:
  SERVICE_NAME: bankingapp-frontend
  REGION: us-central1
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bankingapp-frontend:latest
  TIMEOUT: 30s
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    permissions:
      contents: 'read'
      id-token: 'write'
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
 
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
 
      - name: Authenticate Docker to GCR
        env:
          GCP_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "${GCP_KEY}" | docker login -u _json_key --password-stdin https://gcr.io
 
      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          push: true
          tags: ${{ env.IMAGE }}
 
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE }}
          allow-unauthenticated: true
          port: 8080
          timeout: ${{ env.TIMEOUT }}