name: Deploy React Frontend to Cloud Run (Simplified)
 
on:
  workflow_dispatch:
 
env:
  SERVICE_NAME: react-frontend
  REGION: asia-south1
  # The deploy action will automatically push to gcr.io / Artifact Registry.
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    permissions:
      contents: 'read'
      id-token: 'write' # Required for gcloud auth
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      # --- Authentication Setup ---
      - name: Set up Google Cloud CLI and Authenticate
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
 
      # --- Build, Push, and Deploy Frontend ---
      - name: Build, Push, and Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          source: ./frontend/    # Path to your React frontend
          port: 80               # React app served via nginx default port
          flags: --allow-unauthenticated