name: Deploy FastAPI Backend to Cloud Run

on:
  workflow_dispatch:

env:
  SERVICE_NAME: bankingapp-backend
  REGION: asia-south1
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bankingapp-backend:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Authenticate Docker to GCR
        run: |
          printf '%s' "${{ secrets.GCP_SA_KEY }}" > "${HOME}/gcloud-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcloud-key.json"
          gcloud auth configure-docker --quiet


      # - name: Authenticate Docker to GCR
      #   run: |
      #     echo "${{ secrets.GCP_SA_KEY }}" > "${HOME}/gcloud-key.json"
      #     gcloud auth activate-service-account --key-file="${HOME}/gcloud-key.json"
      #     gcloud auth configure-docker --quiet


      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          push: true
          tags: ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE }}
          allow-unauthenticated: true
          port: 8000
