name: Deploy FastAPI Backend to Cloud Run

on:
  workflow_dispatch:

env:
  SERVICE_NAME: bankingapp-backend
  REGION: us-central1
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bankingapp-backend:latest
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Authenticate Docker to GCP Artifact Registry/GCR
        env:
          # 1. Assign the secret to an environment variable in this step
          #    This often helps with handling multi-line strings.
          GCP_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          # 2. Use the assigned variable and pipe it directly to docker login.
          #    The -u _json_key and --password-stdin are critical.
          echo "${GCP_KEY}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          push: true
          tags: ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE }}
          allow-unauthenticated: true
          port: 8000
          env-vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
